/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : HTMLTOX
 #	author : miyako
 #	2015/11/19
 #
 # --------------------------------------------------------------------------------*/

#include "wkhtmltox/pdf.h"
#include "wkhtmltox/image.h"

// --- HTMLTOX
void HTML_Convert(sLONG_PTR *pResult, PackagePtr pParams);

#define HTMLTOX_Format_PDF 0
#define HTMLTOX_Format_PS 1
#define HTMLTOX_Format_PNG 2
#define HTMLTOX_Format_JPG 3
#define HTMLTOX_Format_BMP 4
#define HTMLTOX_Format_SVG 5

#define CMU_Test_path_name 476
#define CMK_Is_a_document 1

typedef PA_long32 process_number_t;
typedef PA_long32 method_id_t;
typedef PA_long32 progress_id_t;

void listenerLoop(void);
void listenerLoopStart(void);
void listenerLoopFinish(void);
void listenerLoopExecute(void);
void listenerLoopExecuteMethod(void);