/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : HTMLTOX
 #	author : miyako
 #	2016/11/21
 #
 # --------------------------------------------------------------------------------*/

#include "wkhtmltox_4d.h"

// --- HTMLTOX
void HTML_Convert(sLONG_PTR *pResult, PackagePtr pParams);